# Generated by Django 4.0.4 on 2022-06-02 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreC', models.CharField(max_length=40)),
                ('tipo_cli', models.CharField(max_length=40)),
                ('rama', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreU', models.CharField(max_length=40)),
                ('sector', models.CharField(max_length=40)),
                ('rol', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreP', models.CharField(max_length=40)),
                ('codigoprov', models.IntegerField()),
                ('tipo_prov', models.CharField(max_length=40)),
                ('rama', models.CharField(max_length=40)),
            ],
        ),
    ]
